server:
  port: 8087

spring:
  application:
    name: rabbitmq-hello
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    publisher-confirms: true
#    publisher-returns: true
#    listener:
#      simple:
#        acknowledge-mode: manual
#        concurrency: 1
#        retry:
#          enabled: true

